# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTett1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tett1(self):
    self.driver.get("https://merkabi.ru/?yclid=4684881310590959615")
    self.driver.set_window_size(1036, 556)
    self.driver.find_element(By.CSS_SELECTOR, ".lvl1:nth-child(1) > span > a").click()
    self.driver.find_element(By.LINK_TEXT, "Труба ЭСВ ГОСТ 10704 10х0,6 сталь 0,8 пс").click()
    self.driver.find_element(By.ID, "catalog_add2cart_link").click()
    self.driver.find_element(By.CSS_SELECTOR, "#addItemInCart > .button").click()
    self.driver.find_element(By.LINK_TEXT, "Корзина").click()
    self.driver.find_element(By.CSS_SELECTOR, ".unites_calc_unit .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".unites_calc_unit .plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".current").click()
  
